name: Elixir CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.0.3'
          elixir-version: '1.14.3'
      - name: Install Hex and Rebar
        run: mix local.hex --force && mix local.rebar --force
      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
          path: |
            priv/plts
      - name: Restore dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Restore build cache
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Install dependencies
        run: mix deps.get
      - name: Audit Hex
        run: mix hex.audit
      - name: Check unused deps
        run: mix deps.unlock --check-unused
      - name: Compile dependencies
        run: mix deps.compile
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Check formatting
        run: mix format --check-formatted
      - name: Check code consistency
        run: mix credo
      - name: Run dialyzer
        run: mix dialyzer --format github
      - name: Compile code
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test

    env:
      MIX_ENV: test
      LANG: C.UTF-8
