name: Elixir CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: elixir:1.14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: Install Hex and Rebar
        run: mix local.hex --force && mix local.rebar --force
      - name: Install Alpine SDK
        run: apk add alpine-sdk
      - name: Restore dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Restore build cache
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
      - name: Install dependencies
        run: mix deps.get
      - name: Audit Hex
        run: mix hex.audit
      - name: Check unused deps
        run: mix deps.unlock --check-unused
      - name: Compile dependencies
        run: mix deps.compile
      - name: Compile code
        run: mix compile --warnings-as-errors
      - name: Check formatting
        run: mix format --check-formatted
      - name: Check code consistency
        run: mix credo
      - name: Run tests
        run: mix test

    env:
      MIX_ENV: test
      LANG: C.UTF-8
